### ISSUE TITLE
Can't get last commit in production

### ISSUE THREAD

**Issue by mittalyashu** [node-modules/last-commit-log#15]
It is not able to fetch git data in production ready application.

![Thermal_2owPCZCA0I](https://user-images.githubusercontent.com/29014463/56082014-57259500-5e31-11e9-93a1-593afaacc31c.png)

**Comment by the1sword** [comment]
Not the author but it looks like you're trying to get the latest commit from a branch and/or repo that has no commits in it at all, hence it fails.
